[build]
  # الأمر المسؤول عن تجميع وبناء مشروع Vite
  command = "npm run build"
  
  # المجلد الناتج عن البناء والذي يحتوي على ملفات التشغيل (مهم جداً في Vite)
  publish = "dist"

# هذا الجزء يمنع ظهور الشاشة البيضاء عند التنقل أو تحديث الصفحة
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
